let allImg = [
    './img/1.Sharkie/1.IDLE/1.png',
    './img/1.Sharkie/1.IDLE/2.png',
    './img/1.Sharkie/1.IDLE/3.png',
    './img/1.Sharkie/1.IDLE/4.png',
    './img/1.Sharkie/1.IDLE/5.png',
    './img/1.Sharkie/1.IDLE/6.png',
    './img/1.Sharkie/1.IDLE/7.png',
    './img/1.Sharkie/1.IDLE/8.png',
    './img/1.Sharkie/1.IDLE/9.png',
    './img/1.Sharkie/1.IDLE/10.png',
    './img/1.Sharkie/1.IDLE/11.png',
    './img/1.Sharkie/1.IDLE/12.png',
    './img/1.Sharkie/1.IDLE/13.png',
    './img/1.Sharkie/1.IDLE/14.png',
    './img/1.Sharkie/1.IDLE/15.png',
    './img/1.Sharkie/1.IDLE/16.png',
    './img/1.Sharkie/1.IDLE/17.png',
    './img/1.Sharkie/1.IDLE/18.png',
    './img/1.Sharkie/2.Long_IDLE/1.png',
    './img/1.Sharkie/2.Long_IDLE/2.png',
    './img/1.Sharkie/2.Long_IDLE/3.png',
    './img/1.Sharkie/2.Long_IDLE/4.png',
    './img/1.Sharkie/2.Long_IDLE/5.png',
    './img/1.Sharkie/2.Long_IDLE/6.png',
    './img/1.Sharkie/2.Long_IDLE/7.png',
    './img/1.Sharkie/2.Long_IDLE/8.png',
    './img/1.Sharkie/2.Long_IDLE/9.png',
    './img/1.Sharkie/2.Long_IDLE/10.png',
    './img/1.Sharkie/2.Long_IDLE/11.png',
    './img/1.Sharkie/2.Long_IDLE/12.png',
    './img/1.Sharkie/2.Long_IDLE/13.png',
    './img/1.Sharkie/2.Long_IDLE/14.png',
    './img/1.Sharkie/3.Swim/1.png',
    './img/1.Sharkie/3.Swim/2.png',
    './img/1.Sharkie/3.Swim/3.png',
    './img/1.Sharkie/3.Swim/4.png',
    './img/1.Sharkie/3.Swim/5.png',
    './img/1.Sharkie/3.Swim/6.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Bubble/1.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Bubble/2.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Bubble/3.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Bubble/4.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/Whitout bubbles/1.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/Whitout bubbles/2.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/Whitout bubbles/3.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/Whitout bubbles/4.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/Whitout bubbles/5.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/Whitout bubbles/6.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/Whitout bubbles/7.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/Whitout bubbles/8.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/1.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/2.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/3.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/4.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/5.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/6.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/7.png',
    './img/1.Sharkie/4.Attack/Bubble trap/For Whale/8.png',
    './img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/1.png',
    './img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/2.png',
    './img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/3.png',
    './img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/4.png',
    './img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/5.png',
    './img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/6.png',
    './img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/7.png',
    './img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/8.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Op2 (Without Bubbles)/1.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Op2 (Without Bubbles)/2.png',    
    './img/1.Sharkie/4.Attack/Bubble trap/Op2 (Without Bubbles)/3.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Op2 (Without Bubbles)/4.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Op2 (Without Bubbles)/5.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Op2 (Without Bubbles)/6.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Op2 (Without Bubbles)/7.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Poisoned Bubble/1.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Poisoned Bubble/2.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Poisoned Bubble/3.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Poisoned Bubble/4.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Bubble.png',
    './img/1.Sharkie/4.Attack/Bubble trap/Poisoned Bubble (for whale).png',
    './img/1.Sharkie/4.Attack/Fin slap/1.png',
    './img/1.Sharkie/4.Attack/Fin slap/2.png',
    './img/1.Sharkie/4.Attack/Fin slap/3.png',
    './img/1.Sharkie/4.Attack/Fin slap/4.png',
    './img/1.Sharkie/4.Attack/Fin slap/5.png',
    './img/1.Sharkie/4.Attack/Fin slap/6.png',
    './img/1.Sharkie/4.Attack/Fin slap/7.png',
    './img/1.Sharkie/4.Attack/Fin slap/8.png',
    './img/1.Sharkie/4.Attack/Fin slap/5 - Kopie.png',
    './img/1.Sharkie/4.Attack/Fin slap/slap.png',
    './img/1.Sharkie/5.Hurt/1.Poisoned/1.png',
    './img/1.Sharkie/5.Hurt/1.Poisoned/2.png',
    './img/1.Sharkie/5.Hurt/1.Poisoned/3.png',
    './img/1.Sharkie/5.Hurt/1.Poisoned/4.png',
    './img/1.Sharkie/5.Hurt/1.Poisoned/5.png',
    './img/1.Sharkie/5.Hurt/2.Electric shock/1.png',
    './img/1.Sharkie/5.Hurt/2.Electric shock/2.png',
    './img/1.Sharkie/5.Hurt/2.Electric shock/3.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00000.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00001.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00002.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00003.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00004.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00005.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00006.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00007.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00008.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00009.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00010.png',
    './img/1.Sharkie/6.dead/1.Poisoned/sin subir/DES 2_00011.png',
    './img/1.Sharkie/6.dead/1.Poisoned/1.png',
    './img/1.Sharkie/6.dead/1.Poisoned/2.png',
    './img/1.Sharkie/6.dead/1.Poisoned/3.png',
    './img/1.Sharkie/6.dead/1.Poisoned/4.png',
    './img/1.Sharkie/6.dead/1.Poisoned/5.png',
    './img/1.Sharkie/6.dead/1.Poisoned/6.png',
    './img/1.Sharkie/6.dead/1.Poisoned/7.png',
    './img/1.Sharkie/6.dead/1.Poisoned/8.png',
    './img/1.Sharkie/6.dead/1.Poisoned/9.png',
    './img/1.Sharkie/6.dead/1.Poisoned/10.png',
    './img/1.Sharkie/6.dead/1.Poisoned/11.png',
    './img/1.Sharkie/6.dead/1.Poisoned/12.png',
    './img/1.Sharkie/6.dead/2.Electro_shock/1.png',
    './img/1.Sharkie/6.dead/2.Electro_shock/2.png',
    './img/1.Sharkie/6.dead/2.Electro_shock/3.png',
    './img/1.Sharkie/6.dead/2.Electro_shock/4.png',
    './img/1.Sharkie/6.dead/2.Electro_shock/5.png',
    './img/1.Sharkie/6.dead/2.Electro_shock/6.png',
    './img/1.Sharkie/6.dead/2.Electro_shock/7.png',
    './img/1.Sharkie/6.dead/2.Electro_shock/8.png',
    './img/1.Sharkie/6.dead/2.Electro_shock/9.png',
    './img/1.Sharkie/6.dead/2.Electro_shock/10.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/1.swim1.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/1.swim2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/1.swim3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/1.swim4.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/1.swim5.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/2.swim1.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/2.swim2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/2.swim3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/2.swim4.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/2.swim5.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/3.swim1.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/3.swim2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/3.swim3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/3.swim4.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/3.swim5.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/1.transition1.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/1.transition2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/1.transition3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/1.transition4.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/1.transition5.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/2.transition1.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/2.transition2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/2.transition3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/2.transition4.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/2.transition5.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/3.transition1.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/3.transition2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/3.transition3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/3.transition4.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/2.transition/3.transition5.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/1.bubbleswim1.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/1.bubbleswim2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/1.bubbleswim3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/1.bubbleswim4.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/1.bubbleswim5.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/2.bubbleswim1.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/2.bubbleswim2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/2.bubbleswim3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/2.bubbleswim4.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/2.bubbleswim5.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/3.bubbleswim1.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/3.bubbleswim2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/3.bubbleswim3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/3.bubbleswim4.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/3.bubbleswim5.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/4.DIE/1.1.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/4.DIE/1.2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/4.DIE/1.3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/4.DIE/2.2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/4.DIE/2.3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/4.DIE/2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/4.DIE/3.2.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/4.DIE/3.3.png',
    './img/2.Enemy/1.Puffer fish (3 color options)/4.DIE/3.png',
    './img/2.Enemy/2 Jelly fish/Dead/green/g1.png',
    './img/2.Enemy/2 Jelly fish/Dead/green/g2.png',
    './img/2.Enemy/2 Jelly fish/Dead/green/g3.png',
    './img/2.Enemy/2 Jelly fish/Dead/green/g4.png',
    './img/2.Enemy/2 Jelly fish/Dead/Lila/L1.png',
    './img/2.Enemy/2 Jelly fish/Dead/Lila/L2.png',
    './img/2.Enemy/2 Jelly fish/Dead/Lila/L3.png',
    './img/2.Enemy/2 Jelly fish/Dead/Lila/L4.png',
    './img/2.Enemy/2 Jelly fish/Dead/Pink/P1.png',
    './img/2.Enemy/2 Jelly fish/Dead/Pink/P2.png',
    './img/2.Enemy/2 Jelly fish/Dead/Pink/P3.png',
    './img/2.Enemy/2 Jelly fish/Dead/Pink/P4.png',
    './img/2.Enemy/2 Jelly fish/Dead/Yellow/y1.png',
    './img/2.Enemy/2 Jelly fish/Dead/Yellow/y2.png',
    './img/2.Enemy/2 Jelly fish/Dead/Yellow/y3.png',
    './img/2.Enemy/2 Jelly fish/Dead/Yellow/y4.png',
    './img/2.Enemy/2 Jelly fish/Regular damage/Lila 1.png',
    './img/2.Enemy/2 Jelly fish/Regular damage/Lila 2.png',
    './img/2.Enemy/2 Jelly fish/Regular damage/Lila 3.png',
    './img/2.Enemy/2 Jelly fish/Regular damage/Lila 4.png',
    './img/2.Enemy/2 Jelly fish/Regular damage/Yellow 1.png',
    './img/2.Enemy/2 Jelly fish/Regular damage/Yellow 2.png',
    './img/2.Enemy/2 Jelly fish/Regular damage/Yellow 3.png',
    './img/2.Enemy/2 Jelly fish/Regular damage/Yellow 4.png',
    './img/2.Enemy/2 Jelly fish/Súper dangerous/Green 1.png',
    './img/2.Enemy/2 Jelly fish/Súper dangerous/Green 2.png',
    './img/2.Enemy/2 Jelly fish/Súper dangerous/Green 3.png',
    './img/2.Enemy/2 Jelly fish/Súper dangerous/Green 4.png',
    './img/2.Enemy/2 Jelly fish/Súper dangerous/Pink 1.png',
    './img/2.Enemy/2 Jelly fish/Súper dangerous/Pink 2.png',
    './img/2.Enemy/2 Jelly fish/Súper dangerous/Pink 3.png',
    './img/2.Enemy/2 Jelly fish/Súper dangerous/Pink 4.png',
    './img/2.Enemy/3 Final Enemy/1.Introduce/1.png',
    './img/2.Enemy/3 Final Enemy/1.Introduce/2.png',
    './img/2.Enemy/3 Final Enemy/1.Introduce/3.png',
    './img/2.Enemy/3 Final Enemy/1.Introduce/4.png',
    './img/2.Enemy/3 Final Enemy/1.Introduce/5.png',
    './img/2.Enemy/3 Final Enemy/1.Introduce/6.png',
    './img/2.Enemy/3 Final Enemy/1.Introduce/7.png',
    './img/2.Enemy/3 Final Enemy/1.Introduce/8.png',
    './img/2.Enemy/3 Final Enemy/1.Introduce/9.png',
    './img/2.Enemy/3 Final Enemy/1.Introduce/10.png',
    './img/2.Enemy/3 Final Enemy/2.floating/1.png',
    './img/2.Enemy/3 Final Enemy/2.floating/2.png',
    './img/2.Enemy/3 Final Enemy/2.floating/3.png',
    './img/2.Enemy/3 Final Enemy/2.floating/4.png',
    './img/2.Enemy/3 Final Enemy/2.floating/5.png',
    './img/2.Enemy/3 Final Enemy/2.floating/6.png',
    './img/2.Enemy/3 Final Enemy/2.floating/7.png',
    './img/2.Enemy/3 Final Enemy/2.floating/8.png',
    './img/2.Enemy/3 Final Enemy/2.floating/9.png',
    './img/2.Enemy/3 Final Enemy/2.floating/10.png',
    './img/2.Enemy/3 Final Enemy/2.floating/11.png',
    './img/2.Enemy/3 Final Enemy/2.floating/12.png',
    './img/2.Enemy/3 Final Enemy/2.floating/13.png',
    './img/2.Enemy/3 Final Enemy/Attack/1.png',
    './img/2.Enemy/3 Final Enemy/Attack/2.png',
    './img/2.Enemy/3 Final Enemy/Attack/3.png',
    './img/2.Enemy/3 Final Enemy/Attack/4.png',
    './img/2.Enemy/3 Final Enemy/Attack/5.png',
    './img/2.Enemy/3 Final Enemy/Attack/6.png',
    './img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2 copia 6.png',
    './img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2 copia 7.png',
    './img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2 copia 8.png',
    './img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2 copia 9.png',
    './img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2 copia 10.png',
    './img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2.png',
    './img/2.Enemy/3 Final Enemy/Hurt/1.png',
    './img/2.Enemy/3 Final Enemy/Hurt/2.png',
    './img/2.Enemy/3 Final Enemy/Hurt/3.png',
    './img/2.Enemy/3 Final Enemy/Hurt/4.png',
    './img/3. Background/Barrier/1.png',
    './img/3. Background/Barrier/2.png',
    './img/3. Background/Barrier/3.png',
    './img/3. Background/Dark/1.png',
    './img/3. Background/Dark/2.png',
    './img/3. Background/Dark/completo.png',
    './img/3. Background/Layers/1. Light/1.png',
    './img/3. Background/Layers/1. Light/2.png',
    './img/3. Background/Layers/2. Floor/D.png',
    './img/3. Background/Layers/2. Floor/D1.png',
    './img/3. Background/Layers/2. Floor/D2.png',
    './img/3. Background/Layers/2. Floor/L.png',
    './img/3. Background/Layers/2. Floor/L1.png',
    './img/3. Background/Layers/2. Floor/L2.png',
    './img/3. Background/Layers/3.Fondo 1/D.png',
    './img/3. Background/Layers/3.Fondo 1/D1.png',
    './img/3. Background/Layers/3.Fondo 1/D2.png',
    './img/3. Background/Layers/3.Fondo 1/L.png',
    './img/3. Background/Layers/3.Fondo 1/L1.png',
    './img/3. Background/Layers/3.Fondo 1/L2.png',
    './img/3. Background/Layers/4.Fondo 2/D.png',
    './img/3. Background/Layers/4.Fondo 2/D1.png',
    './img/3. Background/Layers/4.Fondo 2/D2.png',
    './img/3. Background/Layers/4.Fondo 2/L.png',
    './img/3. Background/Layers/4.Fondo 2/L1.png',
    './img/3. Background/Layers/4.Fondo 2/L2.png',
    './img/3. Background/Layers/5. Water/D.png',
    './img/3. Background/Layers/5. Water/D1.png',
    './img/3. Background/Layers/5. Water/D2.png',
    './img/3. Background/Layers/5. Water/L.png',
    './img/3. Background/Layers/5. Water/L1.png',
    './img/3. Background/Layers/5. Water/L2.png',
    './img/3. Background/Legacy/Dark/1.png',
    './img/3. Background/Legacy/Dark/2.png',
    './img/3. Background/Legacy/Dark/3.png',
    './img/3. Background/Legacy/Layers/1. Light/1.png',
    './img/3. Background/Legacy/Layers/1. Light/2.png',
    './img/3. Background/Legacy/Layers/1. Light/3.png',
    './img/3. Background/Legacy/Layers/2. Floor/D1.png',
    './img/3. Background/Legacy/Layers/2. Floor/D2.png',
    './img/3. Background/Legacy/Layers/2. Floor/D3.png',
    './img/3. Background/Legacy/Layers/2. Floor/L1.png',
    './img/3. Background/Legacy/Layers/2. Floor/L2.png',
    './img/3. Background/Legacy/Layers/2. Floor/L3.png',
    './img/3. Background/Legacy/Layers/3.Fondo 1/D1.png',
    './img/3. Background/Legacy/Layers/3.Fondo 1/D2.png',
    './img/3. Background/Legacy/Layers/3.Fondo 1/D3.png',
    './img/3. Background/Legacy/Layers/3.Fondo 1/L1.png',
    './img/3. Background/Legacy/Layers/3.Fondo 1/L2.png',
    './img/3. Background/Legacy/Layers/3.Fondo 1/L3.png',
    './img/3. Background/Legacy/Layers/4.Fondo 2/D1.png',
    './img/3. Background/Legacy/Layers/4.Fondo 2/D2.png',
    './img/3. Background/Legacy/Layers/4.Fondo 2/D3.png',
    './img/3. Background/Legacy/Layers/4.Fondo 2/L1.png',
    './img/3. Background/Legacy/Layers/4.Fondo 2/L2.png',
    './img/3. Background/Legacy/Layers/4.Fondo 2/L3.png',
    './img/3. Background/Legacy/Layers/5. Water/d1.png',
    './img/3. Background/Legacy/Layers/5. Water/D2.png',
    './img/3. Background/Legacy/Layers/5. Water/D3.png',
    './img/3. Background/Legacy/Layers/5. Water/L1.png',
    './img/3. Background/Legacy/Layers/5. Water/L2.png',
    './img/3. Background/Legacy/Layers/5. Water/L3.png',
    './img/3. Background/Legacy/Light/1.png',
    './img/3. Background/Legacy/Light/2.png',
    './img/3. Background/Legacy/Light/3.png',
    './img/3. Background/Light/1.png',
    './img/3. Background/Light/2.png',
    './img/3. Background/Light/full.png',
    './img/3. Background/Mesa de trabajo 1.png',
    './img/4. Marcadores/1. Coins/1.png',
    './img/4. Marcadores/1. Coins/2.png',
    './img/4. Marcadores/1. Coins/3.png',
    './img/4. Marcadores/1. Coins/4.png',
    './img/4. Marcadores/green/100_  copia 3.png',
    './img/4. Marcadores/green/100_ copia 5.png',
    './img/4. Marcadores/green/100_ copia 6.png',
    './img/4. Marcadores/orange/0_  copia.png',
    './img/4. Marcadores/orange/20_  copia.png',
    './img/4. Marcadores/orange/40_  copia.png',
    './img/4. Marcadores/orange/60_  copia.png',
    './img/4. Marcadores/orange/80_  copia.png',
    './img/4. Marcadores/orange/100_  copia.png',
    './img/4. Marcadores/Posión/Animada/1.png',
    './img/4. Marcadores/Posión/Animada/2.png',
    './img/4. Marcadores/Posión/Animada/3.png',
    './img/4. Marcadores/Posión/Animada/4.png',
    './img/4. Marcadores/Posión/Animada/5.png',
    './img/4. Marcadores/Posión/Animada/6.png',
    './img/4. Marcadores/Posión/Animada/7.png',
    './img/4. Marcadores/Posión/Animada/8.png',
    './img/6.Botones/Tittles/Game Over/Recurso 9.png',
    './img/6.Botones/Tittles/Game Over/Recurso 10.png',
    './img/6.Botones/Tittles/Game Over/Recurso 11.png',
    './img/6.Botones/Tittles/Game Over/Recurso 12.png',
    './img/6.Botones/Tittles/Game Over/Recurso 13.png',
    './img/6.Botones/Tittles/You win/Mesa de trabajo 1.png',
    './img/6.Botones/Tittles/You win/Recurso 19.png',
    './img/6.Botones/Tittles/You win/Recurso 20.png',
    './img/6.Botones/Tittles/You win/Recurso 21.png',
    './img/6.Botones/Tittles/You win/Recurso 22.png',
    './img/6.Botones/Try again/Mesa de trabajo 1.png',
    './img/bg/bg.jpg',
    './img/bg/pfeil.png',
    ]

    allAudio = [
        './audio/086334_bubblesmp3-47475.mp3',
        './audio/backsound.mp3',
        './audio/bossattack.mp3',
        './audio/bossdie.mp3',
        './audio/bosshit.mp3',
        './audio/bossintro.mp3',
        './audio/bubbleAttack.mp3',
        './audio/bubbleHit.mp3',
        './audio/coin-splash-38989.mp3',
        './audio/coin.mp3',
        './audio/coin2.mp3',
        './audio/collectitem.mp3',
        './audio/dunksplash.mp3',
        './audio/finalenemyintro.mp3',
        './audio/levelComplete.mp3',
        './audio/miss.mp3',
        './audio/raw_bubblingdrink1-101171.mp3',
        './audio/sackCoin.mp3',
        './audio/shock.mp3',
        './audio/slap.mp3',
        './audio/splash-2-100170.mp3',
        './audio/splash-4-46870.mp3',
        './audio/splash-6213.mp3',
        './audio/water-splash-46402.mp3',
        './audio/water-splosh-38143.mp3',
        './audio/youlose.mp3',
        './audio/youWin.mp3',
    ]